# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship



class ModelDtbPage(Base):
        __tablename__ = 'dtb_page'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        master_page_id = Column(INTEGER(10), ForeignKey('dtb_page.id'), nullable=True)
        parent_dtb_page = relationship('ModelDtbPage')
 
        page_name = Column(String(255), nullable=True) 
        url = Column(String(255), nullable=False) 
        file_name = Column(String(255), nullable=True) 
        edit_type = Column(SMALLINT(5), nullable=False, server_default=text("'1'")) 
        author = Column(String(255), nullable=True) 
        description = Column(String(255), nullable=True) 
        keyword = Column(String(255), nullable=True) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        meta_robots = Column(String(255), nullable=True) 
        meta_tags = Column(String(4000), nullable=True) 
        discriminator_type = Column(String(255), nullable=False)