# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_customer import ModelDtbCustomer
from models.model_mtb_country import ModelMtbCountry
from models.model_mtb_pref import ModelMtbPref


class ModelDtbCustomerAddress(Base):
        __tablename__ = 'dtb_customer_address'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        customer_id = Column(INTEGER(10), ForeignKey('dtb_customer.id'), nullable=True)
        dtb_customer = relationship('ModelDtbCustomer', primaryjoin='ModelDtbCustomerAddress.customer_id == ModelDtbCustomer.id', backref='dtb_customer_address_list')
 
        country_id = Column(SMALLINT(5), ForeignKey('mtb_country.id'), nullable=True)
        mtb_country = relationship('ModelMtbCountry', primaryjoin='ModelDtbCustomerAddress.country_id == ModelMtbCountry.id', backref='dtb_customer_address_list')
 
        pref_id = Column(SMALLINT(5), ForeignKey('mtb_pref.id'), nullable=True)
        mtb_pref = relationship('ModelMtbPref', primaryjoin='ModelDtbCustomerAddress.pref_id == ModelMtbPref.id', backref='dtb_customer_address_list')
 
        name01 = Column(String(255), nullable=False) 
        name02 = Column(String(255), nullable=False) 
        kana01 = Column(String(255), nullable=True) 
        kana02 = Column(String(255), nullable=True) 
        company_name = Column(String(255), nullable=True) 
        postal_code = Column(String(8), nullable=True) 
        addr01 = Column(String(255), nullable=True) 
        addr02 = Column(String(255), nullable=True) 
        phone_number = Column(String(14), nullable=True) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)