# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship



class ModelDtbOrderPdf(Base):
        __tablename__ = 'dtb_order_pdf'
 
        member_id = Column(INTEGER(10), primary_key=True, nullable=False) 
        title = Column(String(255), nullable=True) 
        message1 = Column(String(255), nullable=True) 
        message2 = Column(String(255), nullable=True) 
        message3 = Column(String(255), nullable=True) 
        note1 = Column(String(255), nullable=True) 
        note2 = Column(String(255), nullable=True) 
        note3 = Column(String(255), nullable=True) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        visible = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        discriminator_type = Column(String(255), nullable=False)