# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_member import ModelDtbMember


class ModelDtbPayment(Base):
        __tablename__ = 'dtb_payment'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbPayment.creator_id == ModelDtbMember.id', backref='dtb_payment_list')
 
        payment_method = Column(String(255), nullable=True) 
        charge = Column(DECIMAL(12, 2), nullable=True, server_default=text("'0.00'")) 
        rule_max = Column(DECIMAL(12, 2), nullable=True) 
        sort_no = Column(SMALLINT(5), nullable=True) 
        fixed = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        payment_image = Column(String(255), nullable=True) 
        rule_min = Column(DECIMAL(12, 2), nullable=True) 
        method_class = Column(String(255), nullable=True) 
        visible = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)