# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_delivery import ModelDtbDelivery
from models.model_dtb_payment import ModelDtbPayment


class ModelDtbPaymentOption(Base):
        __tablename__ = 'dtb_payment_option'
 
        delivery_id = Column(INTEGER(10), ForeignKey('dtb_delivery.id'), primary_key=True, nullable=False)
        dtb_delivery = relationship('ModelDtbDelivery', primaryjoin='ModelDtbPaymentOption.delivery_id == ModelDtbDelivery.id', backref='dtb_payment_option_list')
 
        payment_id = Column(INTEGER(10), ForeignKey('dtb_payment.id'), primary_key=True, nullable=False)
        dtb_payment = relationship('ModelDtbPayment', primaryjoin='ModelDtbPaymentOption.payment_id == ModelDtbPayment.id', backref='dtb_payment_option_list')
 
        discriminator_type = Column(String(255), nullable=False)