# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship



class ModelDtbPlugin(Base):
        __tablename__ = 'dtb_plugin'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        name = Column(String(255), nullable=False) 
        code = Column(String(255), nullable=False) 
        enabled = Column(TINYINT(3), nullable=False, server_default=text("'0'")) 
        version = Column(String(255), nullable=False) 
        source = Column(String(255), nullable=False) 
        initialized = Column(TINYINT(3), nullable=False, server_default=text("'0'")) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)