# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship



class ModelDtbDeliveryDuration(Base):
        __tablename__ = 'dtb_delivery_duration'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        name = Column(String(255), nullable=True) 
        duration = Column(SMALLINT(5), nullable=False, server_default=text("'0'")) 
        sort_no = Column(INTEGER(10), nullable=False) 
        discriminator_type = Column(String(255), nullable=False)