# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_mtb_csv_type import ModelMtbCsvType
from models.model_dtb_member import ModelDtbMember


class ModelDtbCsv(Base):
        __tablename__ = 'dtb_csv'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        csv_type_id = Column(SMALLINT(5), ForeignKey('mtb_csv_type.id'), nullable=True)
        mtb_csv_type = relationship('ModelMtbCsvType', primaryjoin='ModelDtbCsv.csv_type_id == ModelMtbCsvType.id', backref='dtb_csv_list')
 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbCsv.creator_id == ModelDtbMember.id', backref='dtb_csv_list')
 
        entity_name = Column(String(255), nullable=False) 
        field_name = Column(String(255), nullable=False) 
        reference_field_name = Column(String(255), nullable=True) 
        disp_name = Column(String(255), nullable=False) 
        sort_no = Column(SMALLINT(5), nullable=False) 
        enabled = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)