# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_delivery import ModelDtbDelivery
from models.model_mtb_pref import ModelMtbPref


class ModelDtbDeliveryFee(Base):
        __tablename__ = 'dtb_delivery_fee'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        delivery_id = Column(INTEGER(10), ForeignKey('dtb_delivery.id'), nullable=True)
        dtb_delivery = relationship('ModelDtbDelivery', primaryjoin='ModelDtbDeliveryFee.delivery_id == ModelDtbDelivery.id', backref='dtb_delivery_fee_list')
 
        pref_id = Column(SMALLINT(5), ForeignKey('mtb_pref.id'), nullable=True)
        mtb_pref = relationship('ModelMtbPref', primaryjoin='ModelDtbDeliveryFee.pref_id == ModelMtbPref.id', backref='dtb_delivery_fee_list')
 
        fee = Column(DECIMAL(12, 2), nullable=False) 
        discriminator_type = Column(String(255), nullable=False)