# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_mtb_device_type import ModelMtbDeviceType


class ModelDtbBlock(Base):
        __tablename__ = 'dtb_block'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        device_type_id = Column(SMALLINT(5), ForeignKey('mtb_device_type.id'), nullable=True)
        mtb_device_type = relationship('ModelMtbDeviceType', primaryjoin='ModelDtbBlock.device_type_id == ModelMtbDeviceType.id', backref='dtb_block_list')
 
        block_name = Column(String(255), nullable=True) 
        file_name = Column(String(255), nullable=False) 
        use_controller = Column(TINYINT(3), nullable=False, server_default=text("'0'")) 
        deletable = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)