# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_member import ModelDtbMember


class ModelDtbNews(Base):
        __tablename__ = 'dtb_news'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbNews.creator_id == ModelDtbMember.id', backref='dtb_news_list')
 
        publish_date = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        title = Column(String(255), nullable=False) 
        description = Column(LONGTEXT, nullable=True) 
        url = Column(String(4000), nullable=True) 
        link_method = Column(TINYINT(3), nullable=False, server_default=text("'0'")) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        visible = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        discriminator_type = Column(String(255), nullable=False)