# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_mtb_customer_status import ModelMtbCustomerStatus
from models.model_mtb_sex import ModelMtbSex
from models.model_mtb_job import ModelMtbJob
from models.model_mtb_country import ModelMtbCountry
from models.model_mtb_pref import ModelMtbPref


class ModelDtbCustomer(Base):
        __tablename__ = 'dtb_customer'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        customer_status_id = Column(SMALLINT(5), ForeignKey('mtb_customer_status.id'), nullable=True)
        mtb_customer_status = relationship('ModelMtbCustomerStatus', primaryjoin='ModelDtbCustomer.customer_status_id == ModelMtbCustomerStatus.id', backref='dtb_customer_list')
 
        sex_id = Column(SMALLINT(5), ForeignKey('mtb_sex.id'), nullable=True)
        mtb_sex = relationship('ModelMtbSex', primaryjoin='ModelDtbCustomer.sex_id == ModelMtbSex.id', backref='dtb_customer_list')
 
        job_id = Column(SMALLINT(5), ForeignKey('mtb_job.id'), nullable=True)
        mtb_job = relationship('ModelMtbJob', primaryjoin='ModelDtbCustomer.job_id == ModelMtbJob.id', backref='dtb_customer_list')
 
        country_id = Column(SMALLINT(5), ForeignKey('mtb_country.id'), nullable=True)
        mtb_country = relationship('ModelMtbCountry', primaryjoin='ModelDtbCustomer.country_id == ModelMtbCountry.id', backref='dtb_customer_list')
 
        pref_id = Column(SMALLINT(5), ForeignKey('mtb_pref.id'), nullable=True)
        mtb_pref = relationship('ModelMtbPref', primaryjoin='ModelDtbCustomer.pref_id == ModelMtbPref.id', backref='dtb_customer_list')
 
        name01 = Column(String(255), nullable=False) 
        name02 = Column(String(255), nullable=False) 
        kana01 = Column(String(255), nullable=True) 
        kana02 = Column(String(255), nullable=True) 
        company_name = Column(String(255), nullable=True) 
        postal_code = Column(String(8), nullable=True) 
        addr01 = Column(String(255), nullable=True) 
        addr02 = Column(String(255), nullable=True) 
        email = Column(String(255), nullable=False) 
        phone_number = Column(String(14), nullable=True) 
        birth = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        password = Column(String(255), nullable=False) 
        salt = Column(String(255), nullable=True) 
        secret_key = Column(String(255), unique=True, nullable=False) 
        first_buy_date = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        last_buy_date = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        buy_times = Column(DECIMAL(10, 0), nullable=True, server_default=text("'0'")) 
        buy_total = Column(DECIMAL(12, 2), nullable=True, server_default=text("'0.00'")) 
        note = Column(String(4000), nullable=True) 
        reset_key = Column(String(255), nullable=True) 
        reset_expire = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        point = Column(DECIMAL(12, 0), nullable=False, server_default=text("'0'")) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)