# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_customer import ModelDtbCustomer
from models.model_dtb_product import ModelDtbProduct


class ModelDtbCustomerFavoriteProduct(Base):
        __tablename__ = 'dtb_customer_favorite_product'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        customer_id = Column(INTEGER(10), ForeignKey('dtb_customer.id'), nullable=True)
        dtb_customer = relationship('ModelDtbCustomer', primaryjoin='ModelDtbCustomerFavoriteProduct.customer_id == ModelDtbCustomer.id', backref='dtb_customer_favorite_product_list')
 
        product_id = Column(INTEGER(10), ForeignKey('dtb_product.id'), nullable=True)
        dtb_product = relationship('ModelDtbProduct', primaryjoin='ModelDtbCustomerFavoriteProduct.product_id == ModelDtbProduct.id', backref='dtb_customer_favorite_product_list')
 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)