# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_delivery import ModelDtbDelivery


class ModelDtbDeliveryTime(Base):
        __tablename__ = 'dtb_delivery_time'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        delivery_id = Column(INTEGER(10), ForeignKey('dtb_delivery.id'), nullable=True)
        dtb_delivery = relationship('ModelDtbDelivery', primaryjoin='ModelDtbDeliveryTime.delivery_id == ModelDtbDelivery.id', backref='dtb_delivery_time_list')
 
        delivery_time = Column(String(255), nullable=False) 
        sort_no = Column(SMALLINT(5), nullable=False) 
        visible = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)