# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_mtb_country import ModelMtbCountry
from models.model_mtb_pref import ModelMtbPref


class ModelDtbBaseInfo(Base):
        __tablename__ = 'dtb_base_info'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        country_id = Column(SMALLINT(5), ForeignKey('mtb_country.id'), nullable=True)
        mtb_country = relationship('ModelMtbCountry', primaryjoin='ModelDtbBaseInfo.country_id == ModelMtbCountry.id', backref='dtb_base_info_list')
 
        pref_id = Column(SMALLINT(5), ForeignKey('mtb_pref.id'), nullable=True)
        mtb_pref = relationship('ModelMtbPref', primaryjoin='ModelDtbBaseInfo.pref_id == ModelMtbPref.id', backref='dtb_base_info_list')
 
        company_name = Column(String(255), nullable=True) 
        company_kana = Column(String(255), nullable=True) 
        postal_code = Column(String(8), nullable=True) 
        addr01 = Column(String(255), nullable=True) 
        addr02 = Column(String(255), nullable=True) 
        phone_number = Column(String(14), nullable=True) 
        business_hour = Column(String(255), nullable=True) 
        email01 = Column(String(255), nullable=True) 
        email02 = Column(String(255), nullable=True) 
        email03 = Column(String(255), nullable=True) 
        email04 = Column(String(255), nullable=True) 
        shop_name = Column(String(255), nullable=True) 
        shop_kana = Column(String(255), nullable=True) 
        shop_name_eng = Column(String(255), nullable=True) 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        good_traded = Column(String(4000), nullable=True) 
        message = Column(String(4000), nullable=True) 
        delivery_free_amount = Column(DECIMAL(12, 2), nullable=True) 
        delivery_free_quantity = Column(INTEGER(10), nullable=True) 
        option_mypage_order_status_display = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        option_nostock_hidden = Column(TINYINT(3), nullable=False, server_default=text("'0'")) 
        option_favorite_product = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        option_product_delivery_fee = Column(TINYINT(3), nullable=False, server_default=text("'0'")) 
        option_product_tax_rule = Column(TINYINT(3), nullable=False, server_default=text("'0'")) 
        option_customer_activate = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        option_remember_me = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        authentication_key = Column(String(255), nullable=True) 
        php_path = Column(String(255), nullable=True) 
        option_point = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        basic_point_rate = Column(DECIMAL(10, 0), nullable=True, server_default=text("'1'")) 
        point_conversion_rate = Column(DECIMAL(10, 0), nullable=True, server_default=text("'1'")) 
        discriminator_type = Column(String(255), nullable=False)