# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_member import ModelDtbMember


class ModelDtbMailTemplate(Base):
        __tablename__ = 'dtb_mail_template'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbMailTemplate.creator_id == ModelDtbMember.id', backref='dtb_mail_template_list')
 
        name = Column(String(255), nullable=True) 
        file_name = Column(String(255), nullable=True) 
        mail_subject = Column(String(255), nullable=True) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)