# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_member import ModelDtbMember


class ModelDtbCategory(Base):
        __tablename__ = 'dtb_category'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        parent_category_id = Column(INTEGER(10), ForeignKey('dtb_category.id'), nullable=True)
        parent_dtb_category = relationship('ModelDtbCategory')
 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbCategory.creator_id == ModelDtbMember.id', backref='dtb_category_list')
 
        category_name = Column(String(255), nullable=False) 
        hierarchy = Column(INTEGER(10), nullable=False) 
        sort_no = Column(INTEGER(10), nullable=False) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)