# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_member import ModelDtbMember
from models.model_mtb_sale_type import ModelMtbSaleType


class ModelDtbDelivery(Base):
        __tablename__ = 'dtb_delivery'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbDelivery.creator_id == ModelDtbMember.id', backref='dtb_delivery_list')
 
        sale_type_id = Column(SMALLINT(5), ForeignKey('mtb_sale_type.id'), nullable=True)
        mtb_sale_type = relationship('ModelMtbSaleType', primaryjoin='ModelDtbDelivery.sale_type_id == ModelMtbSaleType.id', backref='dtb_delivery_list')
 
        name = Column(String(255), nullable=True) 
        service_name = Column(String(255), nullable=True) 
        description = Column(String(4000), nullable=True) 
        confirm_url = Column(String(4000), nullable=True) 
        sort_no = Column(INTEGER(10), nullable=True) 
        visible = Column(TINYINT(3), nullable=False, server_default=text("'1'")) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)