# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_customer import ModelDtbCustomer


class ModelDtbCart(Base):
        __tablename__ = 'dtb_cart'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        customer_id = Column(INTEGER(10), ForeignKey('dtb_customer.id'), nullable=True)
        dtb_customer = relationship('ModelDtbCustomer', primaryjoin='ModelDtbCart.customer_id == ModelDtbCustomer.id', backref='dtb_cart_list')
 
        cart_key = Column(String(255), nullable=True) 
        pre_order_id = Column(String(255), unique=True, nullable=True) 
        total_price = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        delivery_fee_total = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        sort_no = Column(SMALLINT(5), nullable=True) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        add_point = Column(DECIMAL(12, 0), nullable=False, server_default=text("'0'")) 
        use_point = Column(DECIMAL(12, 0), nullable=False, server_default=text("'0'")) 
        discriminator_type = Column(String(255), nullable=False)