# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_order import ModelDtbOrder
from models.model_dtb_member import ModelDtbMember


class ModelDtbMailHistory(Base):
        __tablename__ = 'dtb_mail_history'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        order_id = Column(INTEGER(10), ForeignKey('dtb_order.id'), nullable=True)
        dtb_order = relationship('ModelDtbOrder', primaryjoin='ModelDtbMailHistory.order_id == ModelDtbOrder.id', backref='dtb_mail_history_list')
 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbMailHistory.creator_id == ModelDtbMember.id', backref='dtb_mail_history_list')
 
        send_date = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        mail_subject = Column(String(255), nullable=True) 
        mail_body = Column(LONGTEXT, nullable=True) 
        mail_html_body = Column(LONGTEXT, nullable=True) 
        discriminator_type = Column(String(255), nullable=False)