# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_customer import ModelDtbCustomer
from models.model_mtb_country import ModelMtbCountry
from models.model_mtb_pref import ModelMtbPref
from models.model_mtb_sex import ModelMtbSex
from models.model_mtb_job import ModelMtbJob
from models.model_dtb_payment import ModelDtbPayment
from models.model_mtb_device_type import ModelMtbDeviceType


class ModelDtbOrder(Base):
        __tablename__ = 'dtb_order'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        customer_id = Column(INTEGER(10), ForeignKey('dtb_customer.id'), nullable=True)
        dtb_customer = relationship('ModelDtbCustomer', primaryjoin='ModelDtbOrder.customer_id == ModelDtbCustomer.id', backref='dtb_order_list')
 
        country_id = Column(SMALLINT(5), ForeignKey('mtb_country.id'), nullable=True)
        mtb_country = relationship('ModelMtbCountry', primaryjoin='ModelDtbOrder.country_id == ModelMtbCountry.id', backref='dtb_order_list')
 
        pref_id = Column(SMALLINT(5), ForeignKey('mtb_pref.id'), nullable=True)
        mtb_pref = relationship('ModelMtbPref', primaryjoin='ModelDtbOrder.pref_id == ModelMtbPref.id', backref='dtb_order_list')
 
        sex_id = Column(SMALLINT(5), ForeignKey('mtb_sex.id'), nullable=True)
        mtb_sex = relationship('ModelMtbSex', primaryjoin='ModelDtbOrder.sex_id == ModelMtbSex.id', backref='dtb_order_list')
 
        job_id = Column(SMALLINT(5), ForeignKey('mtb_job.id'), nullable=True)
        mtb_job = relationship('ModelMtbJob', primaryjoin='ModelDtbOrder.job_id == ModelMtbJob.id', backref='dtb_order_list')
 
        payment_id = Column(INTEGER(10), ForeignKey('dtb_payment.id'), nullable=True)
        dtb_payment = relationship('ModelDtbPayment', primaryjoin='ModelDtbOrder.payment_id == ModelDtbPayment.id', backref='dtb_order_list')
 
        device_type_id = Column(SMALLINT(5), ForeignKey('mtb_device_type.id'), nullable=True)
        mtb_device_type = relationship('ModelMtbDeviceType', primaryjoin='ModelDtbOrder.device_type_id == ModelMtbDeviceType.id', backref='dtb_order_list')
 
        pre_order_id = Column(String(255), unique=True, nullable=True) 
        order_no = Column(String(255), nullable=True) 
        message = Column(String(4000), nullable=True) 
        name01 = Column(String(255), nullable=False) 
        name02 = Column(String(255), nullable=False) 
        kana01 = Column(String(255), nullable=True) 
        kana02 = Column(String(255), nullable=True) 
        company_name = Column(String(255), nullable=True) 
        email = Column(String(255), nullable=True) 
        phone_number = Column(String(14), nullable=True) 
        postal_code = Column(String(8), nullable=True) 
        addr01 = Column(String(255), nullable=True) 
        addr02 = Column(String(255), nullable=True) 
        birth = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        subtotal = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        discount = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        delivery_fee_total = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        charge = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        tax = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        total = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        payment_total = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        payment_method = Column(String(255), nullable=True) 
        note = Column(String(4000), nullable=True) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        order_date = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        payment_date = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        currency_code = Column(String(255), nullable=True) 
        complete_message = Column(LONGTEXT, nullable=True) 
        complete_mail_message = Column(LONGTEXT, nullable=True) 
        add_point = Column(DECIMAL(12, 0), nullable=False, server_default=text("'0'")) 
        use_point = Column(DECIMAL(12, 0), nullable=False, server_default=text("'0'")) 
        order_status_id = Column(SMALLINT(5), nullable=True) 
        discriminator_type = Column(String(255), nullable=False)