# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_product_class import ModelDtbProductClass
from models.model_dtb_cart import ModelDtbCart


class ModelDtbCartItem(Base):
        __tablename__ = 'dtb_cart_item'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        product_class_id = Column(INTEGER(10), ForeignKey('dtb_product_class.id'), nullable=True)
        dtb_product_class = relationship('ModelDtbProductClass', primaryjoin='ModelDtbCartItem.product_class_id == ModelDtbProductClass.id', backref='dtb_cart_item_list')
 
        cart_id = Column(INTEGER(10), ForeignKey('dtb_cart.id'), nullable=True)
        dtb_cart = relationship('ModelDtbCart', primaryjoin='ModelDtbCartItem.cart_id == ModelDtbCart.id', backref='dtb_cart_item_list')
 
        price = Column(DECIMAL(12, 2), nullable=False, server_default=text("'0.00'")) 
        quantity = Column(DECIMAL(10, 0), nullable=False, server_default=text("'0'")) 
        point_rate = Column(DECIMAL(10, 0), nullable=True) 
        discriminator_type = Column(String(255), nullable=False)