# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_mtb_work import ModelMtbWork
from models.model_mtb_authority import ModelMtbAuthority


class ModelDtbMember(Base):
        __tablename__ = 'dtb_member'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        work_id = Column(SMALLINT(5), ForeignKey('mtb_work.id'), nullable=True)
        mtb_work = relationship('ModelMtbWork', primaryjoin='ModelDtbMember.work_id == ModelMtbWork.id', backref='dtb_member_list')
 
        authority_id = Column(SMALLINT(5), ForeignKey('mtb_authority.id'), nullable=True)
        mtb_authority = relationship('ModelMtbAuthority', primaryjoin='ModelDtbMember.authority_id == ModelMtbAuthority.id', backref='dtb_member_list')
 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        parent_dtb_member = relationship('ModelDtbMember')
 
        name = Column(String(255), nullable=True) 
        department = Column(String(255), nullable=True) 
        login_id = Column(String(255), nullable=False) 
        password = Column(String(255), nullable=False) 
        salt = Column(String(255), nullable=True) 
        sort_no = Column(SMALLINT(5), nullable=False) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        login_date = Column(DateTime, nullable=True, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)