# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_mtb_authority import ModelMtbAuthority
from models.model_dtb_member import ModelDtbMember


class ModelDtbAuthorityRole(Base):
        __tablename__ = 'dtb_authority_role'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        authority_id = Column(SMALLINT(5), ForeignKey('mtb_authority.id'), nullable=True)
        mtb_authority = relationship('ModelMtbAuthority', primaryjoin='ModelDtbAuthorityRole.authority_id == ModelMtbAuthority.id', backref='dtb_authority_role_list')
 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbAuthorityRole.creator_id == ModelDtbMember.id', backref='dtb_authority_role_list')
 
        deny_url = Column(String(4000), nullable=False) 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        update_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)