# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_product import ModelDtbProduct
from models.model_dtb_tag import ModelDtbTag
from models.model_dtb_member import ModelDtbMember


class ModelDtbProductTag(Base):
        __tablename__ = 'dtb_product_tag'
 
        id = Column(INTEGER(10), primary_key=True, nullable=False) 
        product_id = Column(INTEGER(10), ForeignKey('dtb_product.id'), nullable=True)
        dtb_product = relationship('ModelDtbProduct', primaryjoin='ModelDtbProductTag.product_id == ModelDtbProduct.id', backref='dtb_product_tag_list')
 
        tag_id = Column(INTEGER(10), ForeignKey('dtb_tag.id'), nullable=True)
        dtb_tag = relationship('ModelDtbTag', primaryjoin='ModelDtbProductTag.tag_id == ModelDtbTag.id', backref='dtb_product_tag_list')
 
        creator_id = Column(INTEGER(10), ForeignKey('dtb_member.id'), nullable=True)
        dtb_member = relationship('ModelDtbMember', primaryjoin='ModelDtbProductTag.creator_id == ModelDtbMember.id', backref='dtb_product_tag_list')
 
        create_date = Column(DateTime, nullable=False, comment='(DC2Type:datetimetz)') 
        discriminator_type = Column(String(255), nullable=False)