# The file has been generated by tool- nguyennt2@rikkeisoft.com
from config.database import Base
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.mysql import DECIMAL, INTEGER, SMALLINT, TINYINT, LONGTEXT, TEXT
from sqlalchemy.orm import relationship

from models.model_dtb_page import ModelDtbPage
from models.model_dtb_layout import ModelDtbLayout


class ModelDtbPageLayout(Base):
        __tablename__ = 'dtb_page_layout'
 
        page_id = Column(INTEGER(10), ForeignKey('dtb_page.id'), primary_key=True, nullable=False)
        dtb_page = relationship('ModelDtbPage', primaryjoin='ModelDtbPageLayout.page_id == ModelDtbPage.id', backref='dtb_page_layout_list')
 
        layout_id = Column(INTEGER(10), ForeignKey('dtb_layout.id'), primary_key=True, nullable=False)
        dtb_layout = relationship('ModelDtbLayout', primaryjoin='ModelDtbPageLayout.layout_id == ModelDtbLayout.id', backref='dtb_page_layout_list')
 
        sort_no = Column(SMALLINT(5), nullable=False) 
        discriminator_type = Column(String(255), nullable=False)